spring.application.name=landvn-backend

spring.profiles.active=${SPRING_PROFILE:dev}

server.port=${PORT:8080}

spring.jackson.serialization.fail-on-empty-beans=false

server.tomcat.max-threads=50
server.tomcat.accept-count=100