# =========================
# DATABASE PROD
# =========================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# update / validate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# =========================
# CONNECTION POOL
# =========================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=300000

# =========================
# WEBSOCKET / PROXY
# =========================

server.forward-headers-strategy=framework
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
