# =========================
# DATABASE LOCAL
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/landvn
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# LOGGING
# =========================

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# =========================
# WEBSOCKET
# =========================

server.forward-headers-strategy=framework